version: 2

models:
  - name: subscription_created
    description: "Captures all CREATED events for subscriptions."
    columns:
      - name: subscription_id
        description: "Unique ID of the subscription."

  - name: subscription_cancelled
    description: "Captures all CANCELLED events for subscriptions."
    columns:
      - name: subscription_id
        description: "Unique ID of the subscription."

  - name: subscription_expired
    description: "Captures all EXPIRED events for subscriptions."
    columns:
      - name: subscription_id
        description: "Unique ID of the subscription."

  - name: subscription_fact_table
    description: "Joins all subscription events into a unified fact table."
    columns:
      - name: subscription_id
        description: "Unique ID of the subscription."